### ISSUE TITLE
Large Forecasts can Overflow on Small Screens

### ISSUE THREAD

**Issue by kjcjohnson** [packrat386/boreas#7]
See screenshot. I had a large forecast summary today that overflowed the box on my device.

![Screenshot_20230811-074629~2](https://github.com/packrat386/boreas/assets/3466183/422cb66f-9148-4a23-8011-86a5ec094dfd)

Truncating the text would be no good, and embiggening the box might look bad. Not sure.

**Comment by packrat386** [comment]
I have a fix in the works to embiggen the box on smaller screens. Should be making a v0.2.x shortly.

**Comment by packrat386** [comment]
Added a media query to make the height a little higher on smaller screens. If that's still getting overflowed I'll have to look into `min-height` or something.
